### ISSUE TITLE
Falling Anvil and Lightning Damage isn't logged

### ISSUE THREAD

**Issue by slendy0** [Turqmelon/MelonDamageLib#4]
When you are damaged by a falling anvil or a lightning strike the damage isn't logged. Therefore when you die if you weren't damaged by anything in that last 5 seconds it wouldn't print any message

**Comment by slendy0** [comment]
Falling Anvil and Lightning Damage are the only Damage types that I have discovered that don't log

**Comment by Turqmelon** [comment]
Additional damage types can be submitted via PR, but I don't plan on adding extra damage types (especially rare ones) such as those at this time.
