### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by KnightDev** [Turqmelon/MelonDamageLib#6]
When I attempt to add this project into Eclipse, It gives me over around 100 errors and 300 warnings. What was used to create this in the first place and if you know, which is the best way to go about recompiling it?

**Comment by Turqmelon** [comment]
Just Spigot. This can be seen by simply looking at the imports.

**Comment by KnightDev** [comment]
I've attempted to import it like that. Is there a specific version to compile it against?

**Comment by Turqmelon** [comment]
No.

**Comment by KnightDev** [comment]
KK. Any particular program you use? I use Eclipse but it doesn't like to work with me :D
